import { useEffect, useState } from 'react'
import { Pencil, Plus, Trash2, X } from 'lucide-react'
import { api, type Church, type ChurchPayload } from './api'

const empty:ChurchPayload={name:'',email:'',phone:'',address:'',cnpj:'',principalPastor:''}
export function AdminChurches(){
  const [churches,setChurches]=useState<Church[]>([]);const [editing,setEditing]=useState<Church|null>(null);const [form,setForm]=useState<ChurchPayload>(empty);const [open,setOpen]=useState(false);const [error,setError]=useState('');const [saving,setSaving]=useState(false)
  const load=()=>api.churches().then(setChurches).catch(e=>setError(e instanceof Error?e.message:'Unable to load churches.'))
  useEffect(()=>{void load()},[])
  function create(){setEditing(null);setForm(empty);setOpen(true)}
  function edit(church:Church){setEditing(church);setForm({name:church.name,email:church.email,phone:church.phone,address:church.address,cnpj:church.cnpj,principalPastor:church.principalPastor});setOpen(true)}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{if(editing)await api.updateChurch(editing.id,form);else await api.createChurch(form);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save church.')}finally{setSaving(false)}}
  async function remove(church:Church){if(!window.confirm(`Delete ${church.name}? All related church records will be permanently removed.`))return;try{await api.deleteChurch(church.id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete church.')}}
  return <section className="card admin-churches"><div className="card-title"><div><span className="eyebrow">Super administrator</span><h3>Church workspaces</h3></div><button className="primary" onClick={create}><Plus size={16}/>Add church</button></div>{error&&<div className="form-error">{error}</div>}<div className="church-admin-list">{churches.map(church=><article key={church.id}><div><b>{church.name}</b><small>{church.email} · {church.principalPastor}</small></div><button className="status-button" onClick={()=>edit(church)}><Pencil size={14}/>Edit</button><button className="danger-icon" onClick={()=>remove(church)} aria-label={`Delete ${church.name}`}><Trash2/></button></article>)}{!error&&!churches.length&&<div className="data-message">No churches registered.</div>}</div>{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="person-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Church workspace</span><h2>{editing?'Edit church':'Add church'}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close"><X/></button></div><div className="form-grid"><label className="span-2">Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="span-2">Address<input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>CNPJ<input required value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/></label><label>Principal pastor<input required value={form.principalPastor} onChange={e=>setForm({...form,principalPastor:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save church'}</button></div></form></div>}</section>
}
