import { useEffect, useState } from 'react'
import { CalendarDays, CircleDollarSign, HeartHandshake, MapPin, Plus, Trash2, Users, X } from 'lucide-react'
import { api, type ChurchEvent, type Contribution, type Ministry } from './api'

function StateMessage({loading,error,empty,retry}:{loading:boolean;error:string;empty:string;retry:()=>void}){
  if(loading)return <div className="data-message">Loading…</div>
  if(error)return <div className="data-message error-state"><b>Something went wrong</b><span>{error}</span><button onClick={retry}>Try again</button></div>
  return <div className="data-message"><b>{empty}</b><span>Create the first record to get started.</span></div>
}

export function MinistriesScreen({role}:{role:string}){
  const canManage=['SUPER_ADMIN','CHURCH_ADMIN','PASTOR'].includes(role);void canManage
  const [items,setItems]=useState<Ministry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false)
  const [form,setForm]=useState({name:'',description:'',leaderName:'',active:true})
  async function load(){setLoading(true);setError('');try{setItems(await api.ministries())}catch(e){setError(e instanceof Error?e.message:'Unable to load ministries.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api.createMinistry(form);setOpen(false);setForm({name:'',description:'',leaderName:'',active:true});await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save ministry.')}finally{setSaving(false)}}
  async function remove(id:number){try{await api.deleteMinistry(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete ministry.')}}
  return <><header className="page-heading"><div><span className="eyebrow">Ministries</span><h1>Teams with purpose</h1><p>Equip leaders, care for volunteers, and grow healthy ministries.</p></div>{canManage&&<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>New ministry</button>}</header>
    {!loading&&!error&&items.length>0?<section className="module-grid">{items.map(item=><article className="card module-card" key={item.id}><div className="module-icon"><HeartHandshake/></div><div className="module-copy"><div className="module-title"><h3>{item.name}</h3><span className={`pill ${item.active?'':'muted'}`}>{item.active?'Active':'Inactive'}</span></div><p>{item.description||'No description yet.'}</p><div className="module-meta"><Users size={15}/>{item.leaderName||'Leader not assigned'}</div></div><button className="danger-icon" onClick={()=>remove(item.id)} aria-label="Delete ministry"><Trash2/></button></article>)}</section>:<StateMessage loading={loading} error={error} empty="No ministries yet" retry={load}/>} 
    {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="person-modal" onSubmit={create} onMouseDown={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Ministry</span><h2>Create a ministry</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid"><label className="span-2">Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="span-2">Leader name<input value={form.leaderName} onChange={e=>setForm({...form,leaderName:e.target.value})}/></label><label className="span-2">Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Create ministry'}</button></div></form></div>}
  </>
}

export function CalendarScreen({role}:{role:string}){
  const canManage=['SUPER_ADMIN','CHURCH_ADMIN','PASTOR','LEADER'].includes(role);void canManage
  const [items,setItems]=useState<ChurchEvent[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false)
  const [form,setForm]=useState({title:'',description:'',startsAt:'',endsAt:'',location:'',category:'Worship'})
  async function load(){setLoading(true);setError('');try{setItems(await api.events())}catch(e){setError(e instanceof Error?e.message:'Unable to load events.')}finally{setLoading(false)}}useEffect(()=>{void load()},[])
  async function create(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api.createEvent({...form,endsAt:form.endsAt||undefined});setOpen(false);setForm({title:'',description:'',startsAt:'',endsAt:'',location:'',category:'Worship'});await load()}catch(err){setError(err instanceof Error?err.message:'Unable to create event.')}finally{setSaving(false)}}
  async function remove(id:number){try{await api.deleteEvent(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete event.')}}
  return <><header className="page-heading"><div><span className="eyebrow">Calendar</span><h1>Your shared rhythm</h1><p>Plan services, gatherings, and every moment in between.</p></div>{canManage&&<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>New event</button>}</header>
    {!loading&&!error&&items.length>0?<section className="card timeline">{items.map(item=>{const date=new Date(item.startsAt);return <article className="timeline-event" key={item.id}><div className="timeline-date"><b>{date.getDate()}</b><span>{date.toLocaleString(undefined,{month:'short'}).toUpperCase()}</span></div><div className="timeline-copy"><span className="eyebrow">{item.category||'Event'}</span><h3>{item.title}</h3><p>{date.toLocaleString(undefined,{weekday:'long',hour:'2-digit',minute:'2-digit'})}{item.location?` · ${item.location}`:''}</p>{item.description&&<small>{item.description}</small>}</div><button className="danger-icon" onClick={()=>remove(item.id)} aria-label="Delete event"><Trash2/></button></article>})}</section>:<StateMessage loading={loading} error={error} empty="No events scheduled" retry={load}/>} 
    {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="person-modal" onSubmit={create} onMouseDown={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Calendar</span><h2>Create an event</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid"><label className="span-2">Event title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Starts<input type="datetime-local" required value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Worship</option><option>Community</option><option>Youth</option><option>Leadership</option></select></label><label className="span-2">Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Create event'}</button></div></form></div>}
  </>
}

export function GivingScreen(){
  const [items,setItems]=useState<Contribution[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false)
  const [form,setForm]=useState({donorName:'',amount:0,contributionDate:new Date().toISOString().slice(0,10),type:'Tithe',method:'PIX',notes:''})
  async function load(){setLoading(true);setError('');try{setItems(await api.contributions())}catch(e){setError(e instanceof Error?e.message:'Unable to load contributions.')}finally{setLoading(false)}}useEffect(()=>{void load()},[])
  async function create(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api.createContribution(form);setOpen(false);setForm({...form,donorName:'',amount:0,notes:''});await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save contribution.')}finally{setSaving(false)}}
  async function remove(id:number){try{await api.deleteContribution(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete contribution.')}}
  const total=items.reduce((sum,item)=>sum+Number(item.amount),0)
  return <><header className="page-heading"><div><span className="eyebrow">Giving</span><h1>Generosity at a glance</h1><p>Track contributions and steward every gift with clarity.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Record contribution</button></header>
    <section className="giving-summary"><article className="stat feature"><div><span>Total recorded</span><strong>{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><small>{items.length} contributions</small></div><CircleDollarSign size={34}/></article><article className="stat"><span>Average gift</span><strong>{(items.length?total/items.length:0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><small>Across all recorded gifts</small></article></section>
    {!loading&&!error&&items.length>0?<section className="card contribution-list"><div className="contribution-head"><span>Donor</span><span>Date</span><span>Type</span><span>Method</span><span>Amount</span><span/></div>{items.map(item=><div className="contribution-row" key={item.id}><b>{item.donorName||'Anonymous'}</b><span>{new Date(`${item.contributionDate}T12:00:00`).toLocaleDateString()}</span><span>{item.type}</span><span>{item.method||'—'}</span><strong>{Number(item.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><button className="danger-icon" onClick={()=>remove(item.id)}><Trash2/></button></div>)}</section>:<StateMessage loading={loading} error={error} empty="No contributions recorded" retry={load}/>} 
    {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="person-modal" onSubmit={create} onMouseDown={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Giving</span><h2>Record a contribution</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid"><label className="span-2">Donor name<input value={form.donorName} onChange={e=>setForm({...form,donorName:e.target.value})}/></label><label>Amount<input type="number" min="0.01" step="0.01" required value={form.amount||''} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label>Date<input type="date" required value={form.contributionDate} onChange={e=>setForm({...form,contributionDate:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Tithe</option><option>Offering</option><option>Donation</option><option>Campaign</option></select></label><label>Method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>PIX</option><option>Cash</option><option>Card</option><option>Transfer</option></select></label><label className="span-2">Notes<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save contribution'}</button></div></form></div>}
  </>
}
