import { useEffect, useState } from 'react'
import QRCode from 'qrcode'
import { CheckCircle2, Copy, Heart, X } from 'lucide-react'
import { api } from './api'

type PixConfig={key:string;recipient:string;city:string}

export function PixDonation(){
  const [open,setOpen]=useState(false);const [config,setConfig]=useState<PixConfig|null>(null);const [amount,setAmount]=useState('');const [notes,setNotes]=useState('');const [payload,setPayload]=useState('');const [qr,setQr]=useState('');const [saving,setSaving]=useState(false);const [message,setMessage]=useState('')
  useEffect(()=>{api.pixConfiguration().then(setConfig).catch(()=>undefined)},[])
  useEffect(()=>{const value=Number(amount);if(!config||!Number.isFinite(value)||value<1){setPayload('');setQr('');return}const next=pixPayload(config,value);setPayload(next);QRCode.toDataURL(next,{width:280,margin:2,errorCorrectionLevel:'M'}).then(setQr)},[amount,config])
  async function copy(){if(payload){await navigator.clipboard.writeText(payload);setMessage('PIX code copied.')}}
  async function record(){const value=Number(amount);if(value<1)return;setSaving(true);setMessage('');try{await api.recordPixDonation(value,notes);setMessage('Thank you! Your PIX donation was recorded.');setAmount('');setNotes('');setQr('');setPayload('')}catch(e){setMessage(e instanceof Error?e.message:'Unable to record your donation.')}finally{setSaving(false)}}
  return <><section className="card pix-banner"><div className="pix-heart"><Heart/></div><div><span className="eyebrow">Generosity</span><h2>Donate securely with PIX</h2><p>Scan a QR code or copy the PIX payment code from your banking app.</p></div><button className="primary" onClick={()=>setOpen(true)}>Donate with PIX</button></section>{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><section className="person-modal pix-modal" role="dialog" aria-modal="true" aria-labelledby="pix-title" onMouseDown={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">PIX donation</span><h2 id="pix-title">Support your church</h2></div><button onClick={()=>setOpen(false)} aria-label="Close"><X/></button></div><label className="pix-amount">Donation amount (BRL)<input type="number" min="1" step="0.01" inputMode="decimal" placeholder="50.00" value={amount} onChange={e=>{setAmount(e.target.value);setMessage('')}}/></label>{qr&&<div className="pix-code"><img src={qr} alt={`PIX QR code for R$ ${Number(amount).toFixed(2)}`}/><b>{Number(amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b><small>PIX key: {config?.key}</small><button className="secondary" onClick={copy}><Copy size={16}/>Copy PIX code</button></div>}<label className="pix-notes">Optional note<textarea rows={2} maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p className="pix-warning">Complete the payment in your bank before recording it here. FaithOS does not move money or verify settlement automatically.</p>{message&&<div className={message.startsWith('Thank')?'form-success':'form-error'}>{message}</div>}<div className="modal-actions"><button className="secondary" onClick={()=>setOpen(false)}>Close</button><button className="primary" disabled={!payload||saving} onClick={record}><CheckCircle2 size={16}/>{saving?'Recording…':'I completed the PIX payment'}</button></div></section></div>}</>
}

function field(id:string,value:string){return `${id}${String(value.length).padStart(2,'0')}${value}`}
function clean(value:string,max:number){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9 ]/g,'').toUpperCase().slice(0,max)}
function pixPayload(config:PixConfig,amount:number){const merchant=field('00','BR.GOV.BCB.PIX')+field('01',config.key);let payload=field('00','01')+field('26',merchant)+field('52','0000')+field('53','986')+field('54',amount.toFixed(2))+field('58','BR')+field('59',clean(config.recipient,25))+field('60',clean(config.city,15))+field('62',field('05','***'))+'6304';return payload+crc16(payload)}
function crc16(value:string){let crc=0xffff;for(let index=0;index<value.length;index++){crc^=value.charCodeAt(index)<<8;for(let bit=0;bit<8;bit++)crc=(crc&0x8000)!==0?(crc<<1)^0x1021:crc<<1;crc&=0xffff}return crc.toString(16).toUpperCase().padStart(4,'0')}
