spring.application.name=faithOS

spring.datasource.url=jdbc:postgresql://localhost:5433/faithos
spring.datasource.username=faithos_user
spring.datasource.password=faithos_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false