spring.application.name=faithOS
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/faithos
spring.datasource.username=faithos_user
spring.datasource.password=faithos_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=faithos-super-secret-key-must-have-at-least-32-characters
jwt.expiration=86400000