package com.obysoft.faithOS.service;
import java.io.IOException;import java.util.List;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;
import com.obysoft.faithOS.dto.MinistryMessageResponse;import com.obysoft.faithOS.entity.*;import com.obysoft.faithOS.exception.ResourceNotFoundException;import com.obysoft.faithOS.repository.*;
@Service public class MinistryMessageService{
 private final MinistryMessageRepository messages;private final MinistryRepository ministries;private final CurrentChurchService current;
 public MinistryMessageService(MinistryMessageRepository messages,MinistryRepository ministries,CurrentChurchService current){this.messages=messages;this.ministries=ministries;this.current=current;}
 @Transactional(readOnly=true) public List<MinistryMessageResponse> all(Long ministryId){Ministry m=accessible(ministryId);return messages.findAllByMinistryIdOrderByCreatedAtAsc(m.getId()).stream().map(this::response).toList();}
 @Transactional public MinistryMessageResponse send(Long ministryId,String text,MultipartFile file){Ministry m=accessible(ministryId);if((text==null||text.isBlank())&&(file==null||file.isEmpty()))throw new IllegalArgumentException("Write a message or attach a file.");MinistryMessage value=new MinistryMessage();value.setMinistry(m);value.setSender(current.user());value.setMessage(text==null||text.isBlank()?null:text.trim());if(file!=null&&!file.isEmpty()){if(file.getSize()>10*1024*1024)throw new IllegalArgumentException("Attachment must be 10 MB or smaller.");try{value.setAttachmentName(safe(file.getOriginalFilename()));value.setAttachmentType(file.getContentType());value.setAttachmentSize(file.getSize());value.setAttachmentData(file.getBytes());}catch(IOException e){throw new IllegalStateException("Unable to read attachment.",e);}}return response(messages.save(value));}
 @Transactional(readOnly=true) public MinistryAttachment attachment(Long ministryId,Long messageId){Ministry m=accessible(ministryId);MinistryMessage value=messages.findByIdAndMinistryId(messageId,m.getId()).filter(v->v.getAttachmentData()!=null).orElseThrow(()->new ResourceNotFoundException("Attachment not found."));return new MinistryAttachment(value.getAttachmentData(),value.getAttachmentName(),value.getAttachmentType()==null?"application/octet-stream":value.getAttachmentType());}
 private Ministry accessible(Long id){User user=current.user();Ministry m=ministries.findByIdAndChurchId(id,user.getChurch().getId()).orElseThrow(()->new ResourceNotFoundException("Ministry not found."));boolean leadership=user.getRole()==Role.SUPER_ADMIN||user.getRole()==Role.CHURCH_ADMIN||user.getRole()==Role.PASTOR;boolean member=m.getMembers().stream().anyMatch(v->v.getId().equals(user.getId()));boolean leader=m.getLeader()!=null&&m.getLeader().getId().equals(user.getId());if(!leadership&&!member&&!leader)throw new org.springframework.security.access.AccessDeniedException("You do not belong to this ministry.");return m;}
 private MinistryMessageResponse response(MinistryMessage v){User s=v.getSender();return new MinistryMessageResponse(v.getId(),s.getFirstName()+" "+s.getLastName(),s.getId(),v.getMessage(),v.getAttachmentName(),v.getAttachmentType(),v.getAttachmentSize(),v.getCreatedAt());}
 private String safe(String name){if(name==null||name.isBlank())return "attachment";String n=name.replace('\\','/');n=n.substring(n.lastIndexOf('/')+1);return n.substring(0,Math.min(n.length(),255));}
 public record MinistryAttachment(byte[] data,String name,String contentType){}
}
