ALTER TABLE users ADD COLUMN member_code VARCHAR(50);
CREATE UNIQUE INDEX uq_users_church_member_code ON users(church_id, member_code) WHERE member_code IS NOT NULL;

ALTER TABLE attendance_sessions ADD COLUMN opens_at TIME;
ALTER TABLE attendance_sessions ADD COLUMN on_time_until TIME;
ALTER TABLE attendance_sessions ADD COLUMN closes_at TIME;

CREATE TABLE attendance_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    checked_in_at TIMESTAMP NOT NULL,
    attendance_status VARCHAR(20) NOT NULL,
    check_in_source VARCHAR(20) NOT NULL,
    UNIQUE(session_id, user_id)
);
CREATE INDEX idx_attendance_check_ins_session ON attendance_check_ins(session_id, checked_in_at);

CREATE TABLE absence_motivations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    church_id BIGINT NOT NULL REFERENCES churches(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    absence_date DATE NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    created_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    reviewed_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_absence_motivations_church_date ON absence_motivations(church_id, absence_date DESC);

CREATE TABLE member_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    church_id BIGINT NOT NULL REFERENCES churches(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP
);
CREATE INDEX idx_member_messages_recipient ON member_messages(recipient_id, created_at DESC);
CREATE INDEX idx_member_messages_conversation ON member_messages(sender_id, recipient_id, created_at);
