CREATE TABLE churches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    address VARCHAR(255),
    cnpj VARCHAR(255),
    principal_pastor VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    church_id BIGINT NOT NULL REFERENCES churches(id)
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    gender VARCHAR(255),
    church_id BIGINT REFERENCES churches(id)
);

CREATE TABLE ministries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    leader_name VARCHAR(255),
    active BOOLEAN NOT NULL,
    church_id BIGINT NOT NULL REFERENCES churches(id)
);

CREATE TABLE church_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1500),
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP,
    location VARCHAR(255),
    category VARCHAR(255),
    church_id BIGINT NOT NULL REFERENCES churches(id)
);

CREATE TABLE contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_name VARCHAR(255),
    amount NUMERIC(14, 2) NOT NULL,
    contribution_date DATE NOT NULL,
    type VARCHAR(255) NOT NULL,
    method VARCHAR(255),
    notes VARCHAR(1000),
    church_id BIGINT NOT NULL REFERENCES churches(id)
);

CREATE INDEX idx_users_church_id ON users(church_id);
CREATE INDEX idx_members_church_id ON members(church_id);
CREATE INDEX idx_ministries_church_id ON ministries(church_id);
CREATE INDEX idx_church_events_church_id ON church_events(church_id);
CREATE INDEX idx_contributions_church_id ON contributions(church_id);
