CREATE TABLE attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    attendance_type VARCHAR(40) NOT NULL,
    session_date DATE NOT NULL,
    church_id BIGINT NOT NULL REFERENCES churches(id) ON DELETE CASCADE
);

CREATE TABLE attendance_records (
    session_id BIGINT NOT NULL REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (session_id, user_id)
);

CREATE INDEX idx_attendance_sessions_church_date
    ON attendance_sessions(church_id, session_date DESC);
CREATE INDEX idx_attendance_records_user_id ON attendance_records(user_id);
