CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
    expense_date DATE NOT NULL,
    category VARCHAR(100) NOT NULL,
    payee VARCHAR(255),
    notes VARCHAR(1000),
    church_id BIGINT NOT NULL REFERENCES churches(id) ON DELETE CASCADE
);

CREATE INDEX idx_expenses_church_date ON expenses(church_id, expense_date DESC);
