CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    notification_type VARCHAR(60) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    church_id BIGINT NOT NULL REFERENCES churches(id) ON DELETE CASCADE
);

CREATE TABLE notification_reads (
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (notification_id, user_id)
);

CREATE INDEX idx_notifications_church_created ON notifications(church_id, created_at DESC);
CREATE INDEX idx_notification_reads_user ON notification_reads(user_id);
