CREATE TABLE church_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(255),
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    church_id BIGINT NOT NULL REFERENCES churches(id) ON DELETE CASCADE,
    uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_church_files_church_created ON church_files(church_id, created_at DESC);
